#!/bin/bash
# Script by : 

address=$(wget -qO- icanhazip.com);
Today=`date +%s`
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
ovpntcp="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
ovpnudp="$(netstat -nlpu | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(cat /etc/squid3/squid.conf | grep -i http_port | awk '{print $2}')"
Login=trial`</dev/urandom tr -dc X-Z0-9 | head -c4`
day="1"
password=1

sleep 0.5
echo Creating username : $username
sleep 0.5
echo Setting Password : $password
sleep 0.5
clear

useradd -e `date -d "$expired days" +"%Y-%m-%d"` -s /bin/false -M $Login
usermod -s /bin/false $username
usermod -e  $Expiration $username
egrep "^$username" /etc/passwd >/dev/null
echo -e "$password\n$password\n"|passwd $username &> /dev/null
clear

echo -e ""
echo -e "Thank You For Using Our Services"
echo -e "SSH & OpenVPN Account Info"
echo -e "Username       : $username"
echo -e "Password       : $password"
echo -e "==============================="
echo -e "Host           : $address"
echo -e "OpenSSH        : $opensshport"
echo -e "Dropbear       : $dropbearport"
echo -e "SSL/TLS        : $stunnel4port"
echo -e "Port Squid     : $squidport"
echo -e "OpenVPN        : TCP $ovpntcp http://$address:81/client-tcp-$ovpn.ovpn"
echo -e "OpenVPN        : UDP $ovpnudp http://$address:81/client-udp-$ovpn2.ovpn"
echo -e "OpenVPN        : TLS http://$address:81/client-tcp-tls.ovpn"
echo -e "badvpn         : 7200 - 7400"
echo -e "==============================="
echo -e "Expired On     : $expired"
